# Testing Python Logging Configuration
[loggers]
keys=root,transcendent

[handlers]
keys=consoleHandler

[formatters]
keys=testFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_transcendent]
level=DEBUG
handlers=consoleHandler
qualname=transcendent
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=testFormatter
args=(sys.stdout,)

[formatter_testFormatter]
format=TEST: %(asctime)s - %(name)s - %(levelname)s - %(message)s