# Development Python Logging Configuration
[loggers]
keys=root,transcendent

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=developmentFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_transcendent]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=transcendent
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=developmentFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=developmentFormatter
args=('logs/development.log',)

[formatter_developmentFormatter]
format=DEV: %(asctime)s - %(name)s - %(levelname)s - %(message)s